name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.Profile }}   # <-- FIXED
          user: MdJowelAhmed
          base: header, repositories, activity, community
          config_timezone: Asia/Dhaka

          plugin_isocalendar: yes
          plugin_streak: yes
          plugin_languages: yes
          plugin_languages_details: percentage, bytes-size
          plugin_languages_limit: 6

          plugin_activity: yes
          plugin_activity_limit: 5

          plugin_followup: yes
          plugin_people: yes

          plugin_lines: yes
          plugin_traffic: yes

          plugin_repositories: yes
          plugin_stars: yes
